/*
 * Copyright 2026 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */
package kpt.feature.personalloans

import androidx.compose.runtime.Immutable
import androidx.lifecycle.viewModelScope
import co.touchlab.kermit.Logger
import kotlinx.coroutines.launch
import kotlinx.serialization.Serializable
import kotlinx.serialization.Transient
import kpt.core.analytics.KptAnalyticsTracker
import kpt.core.base.network.NetworkError
import kpt.core.base.network.NetworkResult
import kpt.core.base.observability.CrashReporter
import kpt.core.base.observability.CrashSeverity
import kpt.core.base.security.SessionManager
import kpt.core.base.ui.viewmodel.BaseViewModel
import kpt.core.data.repository.LoanRepository
import kpt.core.model.LoanAccountStatus
import kpt.core.model.LoanStatusFilter
import kpt.core.model.LoanSummary

// MVI stack (State/Event/Action/ViewModel/DI) for the `personal-loans` feature — see
// API.md#viewmodel / #state / #actions / #events / #di for the full generated-symbol contract.
private const val TAG = "PersonalLoansViewModel"

/**
 * Screen-level render state for `personal-loans-screen` — verbatim mirror of
 * `ui.yaml#state_model.PersonalLoansViewModel.screen_state.members`. Derived only (not stored)
 * via [PersonalLoansState.deriveScreenState] — same convention as `LoanListState.screenState` /
 * `LoanRequestState.deriveScreenState()` (keeps `isLoading`/`error`/`loans` the single source of
 * truth instead of a fifth, independently-mutable flag). See API.md#state.
 */
@Serializable
sealed interface PersonalLoansScreenState {
    @Serializable
    data object Loading : PersonalLoansScreenState

    @Serializable
    data object Content : PersonalLoansScreenState

    @Serializable
    data object Empty : PersonalLoansScreenState

    @Serializable
    data object Error : PersonalLoansScreenState
}

/**
 * Error taxonomy for the member-loans read — verbatim mirror of
 * `ui.yaml#state_model.PersonalLoansViewModel.errors.types`. [messageKey] is a composeResources
 * string-resource id (never a raw hardcoded English string, per RULE-IMPL-NO-HARDCODED-STRING-001)
 * resolved by the Screen layer.
 *
 * See API.md#state.
 */
@Serializable
sealed interface LoanError {
    val retry: Boolean
    val messageKey: String

    @Serializable
    data object Network : LoanError {
        override val retry: Boolean = true
        override val messageKey: String = "error_network"
    }

    @Serializable
    data object Server : LoanError {
        override val retry: Boolean = true
        override val messageKey: String = "error_server"
    }

    @Serializable
    data object Unauthorized : LoanError {
        override val retry: Boolean = false
        override val messageKey: String = "error_session_expired"
    }
}

/**
 * MVI state for `PersonalLoansViewModel`. Field set + defaults are a verbatim mirror of
 * `ui.yaml#state_model.PersonalLoansViewModel.state.fields`. [loans]/[error] are `@Transient` —
 * always re-derived from [LoanRepository.getLoansForClient] on (re)mount (offline-first cache via
 * the `loans` SQLDelight table per `data-flow.yaml`, so nothing is visually lost across process
 * death), and [LoanSummary] itself is not `@Serializable`. Mirrors `LoanListState`'s identical
 * `@Transient` convention.
 *
 * **[filteredLoans] — additive beyond the literal `ui.yaml#state.fields` list, mirroring
 * `LoanListState.filteredLoans`'s established precedent** (both are generated by the same
 * `kmp-viewmodel-gen` convention): `ui.yaml#components.filter_chips_row`'s `action_contract`
 * ("client-side filtering of the already-loaded loans list") requires SOME derived field for the
 * Screen layer to render, and storing it (recomputed on both filter-change and load) rather than
 * exposing a `get()`-only extension keeps parity with `LoanListState`'s shipped shape. See
 * API.md#state.
 *
 * **`loan.repaymentSchedule` — confirmed idea-layer gap, flagged not invented:**
 * `ui.yaml#components.loan_card.content.repayment_schedule_section` reads
 * `loan.repaymentSchedule.periods`, but the canonical `core/model` [LoanSummary] domain type
 * carries no `repaymentSchedule` field at all (only a flat `nextRepaymentDate`/`overdueAmount`
 * summary). `data-flow.yaml#entries[on_mount].description` says the schedule is fetched inline via
 * `associations=repaymentSchedule`, but no DTO→domain mapping thread reaches this shared
 * `LoanSummary` type (also used by `loan-list`/`loan-detail`, so widening it is a cross-feature
 * decision, not made unilaterally here). The expand/collapse toggle ([selectedLoanId]) is
 * implemented for real in this ViewModel, but the Screen layer's repayment-schedule panel has
 * nothing to render until `LoanSummary` (or a per-loan companion type) gains a
 * `repaymentSchedule` field. Flagged for the cross-feature repair station
 * (RULE-IMPLEMENT-CROSS-FEATURE-FIT-001 CFF1).
 */
@Serializable
@Immutable
data class PersonalLoansState(
    val clientId: Long = 0L,
    @Transient
    val loans: List<LoanSummary> = emptyList(),
    val selectedLoanId: Long? = null,
    val filterStatus: LoanStatusFilter = LoanStatusFilter.ALL,
    @Transient
    val filteredLoans: List<LoanSummary> = emptyList(),
    val isLoading: Boolean = true,
    val isRefreshing: Boolean = false,
    @Transient
    val error: LoanError? = null,
)

/**
 * Derives [PersonalLoansScreenState] from [PersonalLoansState] — see the type's KDoc for why this
 * is a pure function rather than a stored field (mirrors `LoanRequestState.deriveScreenState()`).
 * `error != null` wins over `loans.isEmpty()` so a failed refresh on an already-empty account
 * still surfaces the error state rather than silently re-showing Empty.
 */
fun PersonalLoansState.deriveScreenState(): PersonalLoansScreenState = when {
    error != null -> PersonalLoansScreenState.Error
    isLoading -> PersonalLoansScreenState.Loading
    loans.isEmpty() -> PersonalLoansScreenState.Empty
    else -> PersonalLoansScreenState.Content
}

/**
 * One-shot side effects emitted by `PersonalLoansViewModel` — verbatim mirror of
 * `ui.yaml#state_model.PersonalLoansViewModel.events.members` (2 members, neither declares a
 * `params` key in ui.yaml, so both are parameterless `data object`s).
 *
 * **[NavigateToLoanRequest] — confirmed idea-layer gap, flagged not invented:** the destination
 * `loan-request` screen's `LoanRequestViewModel` constructor requires `clientId` **and**
 * `savingsBalance` **and** `loanMultiplier` (see `LoanRequestModule`), all threaded via Koin
 * `parametersOf` — but this event carries NO payload (verbatim `ui.yaml#events.members` mirror;
 * `ui.yaml#state_model` declares no `params` for `NavigateToLoanRequest`) and neither
 * `savingsBalance` nor `loanMultiplier` is reachable from [PersonalLoansState] or this ViewModel's
 * declared DI graph (`LoanRepository`, `SessionManager` only — no savings-account repository).
 * `clientId` itself IS already known to the consuming NavHost/Route composable (its own back-stack
 * nav-arg), so that leg of the forward is fine; `savingsBalance` is NOT similarly available. This
 * ViewModel does not fabricate a placeholder balance. Flagged for the cross-feature repair station
 * (RULE-IMPLEMENT-CROSS-FEATURE-FIT-001 CFF1) — the fix is either a savings-balance lookup exposed
 * from `LoanRepository`/a savings repository, or `ui.yaml#nav_params` threading `savingsBalance`
 * through `personal-dashboard` → `personal-loans` → `loan-request`.
 *
 * **[NavigateBack] reachability gap (flagged, not fabricated around):** `ui.yaml#components.top_bar`
 * declares `on_navigation_click.action: NavigateBack`, but `ui.yaml#state_model.actions.members`
 * (the 5-member list [PersonalLoansAction] mirrors verbatim per RULE-IMPL-DEAD-CLICKABLE-001
 * Rule 1) does NOT declare a matching `OnBack` action member — same class of drift as
 * `loan-list`'s/`loan-request`'s documented top-bar gap. [NavigateBack] is therefore declared here
 * (verbatim `events.members` mirror) but never emitted by this ViewModel; the Screen layer's
 * `KptScaffold` back button is expected to invoke the nav-host callback directly (bypassing action
 * dispatch) until the idea-layer adds the missing action member. Flagged for idea-layer correction
 * (RULE-IDEA-ACTION-CONTRACT-001).
 *
 * See API.md#events.
 */
sealed interface PersonalLoansEvent {
    data object NavigateToLoanRequest : PersonalLoansEvent
    data object NavigateBack : PersonalLoansEvent
}

/**
 * User intents dispatched to `PersonalLoansViewModel`. The 5 top-level members are a verbatim
 * mirror of `ui.yaml#state_model.PersonalLoansViewModel.actions.members` —
 * RULE-IMPL-DEAD-CLICKABLE-001 Rule 1. [Internal] is the sanctioned async-result-routing
 * sub-interface (never a user intent) per `training-layer/TRAINING_MASTER.yaml#patterns.actions` —
 * mirrors `LoanRequestAction.Internal`. See API.md#actions.
 */
sealed interface PersonalLoansAction {
    data object OnRefresh : PersonalLoansAction
    data object OnRetry : PersonalLoansAction
    data class OnLoanExpand(val loanId: Long) : PersonalLoansAction
    data class OnFilterChange(val status: LoanStatusFilter) : PersonalLoansAction
    data object OnRequestLoanClick : PersonalLoansAction

    /** Async coroutine result — routed via `trySendAction`, never dispatched by the UI. */
    sealed interface Internal : PersonalLoansAction {
        data class LoansLoaded(
            val result: NetworkResult<List<LoanSummary>, NetworkError>,
            val isRefresh: Boolean,
        ) : Internal
    }
}

/**
 * MVI processor for the member-side "My Loans" list (`business_logic.kind: crud` per ui.yaml — a
 * read-only, non-paginated fetch of the signed-in member's own loans; per
 * RULE-IDEA-IMPL-INTELLIGENCE-001 AC-03i the SP-04 AC-7 analytics/crashReporter/fieldEncryptor
 * injection TRIPLE is not mandatory for `crud`, but [crashReporter] and [analytics] are still
 * wired for real, feature-level observability (SC5), mirroring `LoanListViewModel`'s /
 * `LoanRequestViewModel`'s identical crud-but-observed precedent). No `FieldEncryptor`
 * (`core-base/security`) is injected — [LoanSummary] carries no `@PII`-marked field per the SP-02
 * idea-layer schema.
 *
 * [repository] is consumed directly via [NetworkResult] rather than a Store5
 * `.asScreenStream()`/PagingScreenStream — [LoanRepository.getLoansForClient]'s own KDoc "Store5
 * branch" note (a direct passthrough read with no per-client cache/TTL YET; reconciling into a
 * Store5-backed `PersonalLoansStore` is flagged for Station 3, same as the repository KDoc's own
 * divergence note), same branch as [kpt.feature.loanrequest.LoanRequestViewModel].
 *
 * [sessionManager] is declared in `ui.yaml#state_model.di` and is used for its ONE real capability
 * — `endSession()` on [LoanError.Unauthorized] (mirrors `LoanListViewModel`'s identical wiring for
 * its own `Auth`/401 branch).
 *
 * [clientId] is the `ui.yaml#nav_params` value forwarded from `personal-dashboard`'s
 * `user_taps_loan_card` entry point via Koin `parametersOf(clientId)` (see `di.PersonalLoansModule`)
 * — it seeds [PersonalLoansState.clientId] and scopes every [LoanRepository.getLoansForClient]
 * call.
 *
 * See API.md#viewmodel.
 */
internal class PersonalLoansViewModel(
    private val repository: LoanRepository,
    private val sessionManager: SessionManager,
    private val crashReporter: CrashReporter,
    private val analytics: KptAnalyticsTracker,
    private val clientId: Long,
) : BaseViewModel<PersonalLoansState, PersonalLoansEvent, PersonalLoansAction>(
    initialState = PersonalLoansState(clientId = clientId),
) {

    init {
        crashReporter.recordMessage(
            message = "feature=personal-loans screen=personal-loans-screen clientId=$clientId",
            level = CrashSeverity.Debug,
        )
        analytics.trackLoanOperation(operation = "view_list", loanId = null)
        loadLoans(isRefresh = false)
    }

    override fun handleAction(action: PersonalLoansAction) {
        when (action) {
            PersonalLoansAction.OnRefresh -> handleRefresh()
            PersonalLoansAction.OnRetry -> handleRetry()
            is PersonalLoansAction.OnLoanExpand -> handleLoanExpand(action.loanId)
            is PersonalLoansAction.OnFilterChange -> handleFilterChange(action.status)
            PersonalLoansAction.OnRequestLoanClick -> handleRequestLoanClick()
            is PersonalLoansAction.Internal.LoansLoaded -> handleLoansLoaded(action.result, action.isRefresh)
        }
    }

    // -- on_mount / on_refresh (data-flow.yaml — GET /clients/{clientId}/loans) -----------------

    private fun loadLoans(isRefresh: Boolean) {
        viewModelScope.launch {
            val result = repository.getLoansForClient(clientId)
            trySendAction(PersonalLoansAction.Internal.LoansLoaded(result = result, isRefresh = isRefresh))
        }
    }

    // -- Pull-to-refresh (data-flow.yaml on_refresh: bypass_and_refresh) -------------------------

    private fun handleRefresh() {
        analytics.trackLoanOperation(operation = "refresh", loanId = null)
        Logger.i(TAG) { "pull-to-refresh triggered clientId=$clientId" }
        updateState { copy(isRefreshing = true) }
        loadLoans(isRefresh = true)
    }

    // -- Error-state retry (ui.yaml effect: call_api) ---------------------------------------------

    private fun handleRetry() {
        Logger.i(TAG) { "retry tapped — re-dispatching member loans fetch clientId=$clientId" }
        updateState { copy(error = null, isLoading = true) }
        loadLoans(isRefresh = false)
    }

    // -- Loan card tap (ui.yaml effect: transform_state — toggle expand/collapse) ----------------

    private fun handleLoanExpand(loanId: Long) {
        val nextSelection = if (state.selectedLoanId == loanId) null else loanId
        Logger.d(TAG) { "loan card ${if (nextSelection == null) "collapsed" else "expanded"} loanId=$loanId" }
        updateState { copy(selectedLoanId = nextSelection) }
    }

    // -- Filter chip tap (ui.yaml effect: transform_state, client-side status filter) ------------

    private fun handleFilterChange(status: LoanStatusFilter) {
        Logger.d(TAG) { "filter changed to=$status clientId=$clientId" }
        updateState { copy(filterStatus = status, filteredLoans = loans.filterByStatus(status)) }
    }

    // -- Request-loan FAB / empty-state CTA (ui.yaml effect: navigate, target: loan-request) -----

    private fun handleRequestLoanClick() {
        analytics.trackLoanOperation(operation = "request_view", loanId = null)
        Logger.i(TAG) { "request-loan CTA tapped clientId=$clientId" }
        sendEvent(PersonalLoansEvent.NavigateToLoanRequest)
    }

    // -- Fetch result routing -----------------------------------------------------------------------

    private fun handleLoansLoaded(result: NetworkResult<List<LoanSummary>, NetworkError>, isRefresh: Boolean) {
        when (result) {
            is NetworkResult.Success -> {
                val newLoans = result.data
                Logger.i(TAG) { "loans loaded count=${newLoans.size} clientId=$clientId isRefresh=$isRefresh" }
                updateState {
                    copy(
                        isLoading = false,
                        isRefreshing = false,
                        loans = newLoans,
                        filteredLoans = newLoans.filterByStatus(filterStatus),
                        error = null,
                    )
                }
            }

            is NetworkResult.Error -> {
                val mapped = result.error.toLoanError()
                if (mapped == LoanError.Unauthorized) {
                    crashReporter.recordMessage(
                        message = "personal-loans: session expired (401) clientId=$clientId — clearing session",
                        level = CrashSeverity.Warning,
                    )
                    sessionManager.endSession()
                } else {
                    crashReporter.recordException(
                        throwable = IllegalStateException("personal-loans fetch failed: ${result.error}"),
                        message = "personal-loans: load failed clientId=$clientId networkError=${result.error}",
                    )
                }
                updateState { copy(isLoading = false, isRefreshing = false, error = mapped) }
            }
        }
    }

    /**
     * Client-side status filter — `ui.yaml#components.filter_chips_row`'s `effect: transform_state`.
     * [LoanStatusFilter.ALL] performs no filtering; [LoanStatusFilter.ACTIVE]/[LoanStatusFilter.CLOSED]
     * match 1:1 against [LoanAccountStatus]. `ui.yaml#components.filter_chips_row.chips` only renders
     * three chips (no `OVERDUE` chip — overdue loans surface inline via [LoanSummary.isOverdue] on the
     * ACTIVE card instead), but the [LoanStatusFilter.OVERDUE] branch is kept for exhaustiveness and
     * parity with `LoanListViewModel.filterByStatus`'s identical four-branch shape, since both
     * features share the one [LoanStatusFilter] enum (see `LoanStatusFilter.matches` KDoc in
     * `core/model`).
     */
    private fun List<LoanSummary>.filterByStatus(statusFilter: LoanStatusFilter): List<LoanSummary> =
        when (statusFilter) {
            LoanStatusFilter.ALL -> this
            LoanStatusFilter.ACTIVE -> filter { it.status == LoanAccountStatus.ACTIVE }
            LoanStatusFilter.OVERDUE -> filter { it.status == LoanAccountStatus.OVERDUE }
            LoanStatusFilter.CLOSED -> filter { it.status == LoanAccountStatus.CLOSED }
        }

    /**
     * Disambiguates the transport-level [NetworkError] onto [LoanError] —
     * `ui.yaml#state_model.errors.types` declares only 3 members (`Network`/`Server`/`Unauthorized`),
     * narrower than the 8-value [NetworkError] enum. [NetworkError.REQUEST_TIMEOUT] ->
     * [LoanError.Network]; [NetworkError.UNAUTHORIZED]/[NetworkError.TOO_MANY_REQUESTS] ->
     * [LoanError.Unauthorized] (rate-limiting folded onto the non-retry auth bucket — no dedicated
     * `RateLimited` member is declared); every other value (`BAD_REQUEST`/`NOT_FOUND`/`SERVER`/
     * `SERIALIZATION`/`UNKNOWN`) -> [LoanError.Server] (this screen has no user-editable form, so
     * there is no `Validation` bucket to fold `BAD_REQUEST` into, unlike `LoanRequestViewModel`'s
     * `SubmitError.Validation`). Flagged for the cross-feature repair station
     * (RULE-IMPLEMENT-CROSS-FEATURE-FIT-001 CFF1) if a dedicated `RateLimited`/`Validation` bucket
     * is later needed.
     */
    private fun NetworkError.toLoanError(): LoanError = when (this) {
        NetworkError.REQUEST_TIMEOUT -> LoanError.Network
        NetworkError.UNAUTHORIZED, NetworkError.TOO_MANY_REQUESTS -> LoanError.Unauthorized
        NetworkError.BAD_REQUEST, NetworkError.NOT_FOUND, NetworkError.SERVER,
        NetworkError.SERIALIZATION, NetworkError.UNKNOWN,
        -> LoanError.Server
    }
}
