/*
 * Copyright 2025 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */
package kpt.core.database

import androidx.room3.ConstructedBy
import androidx.room3.Database
import androidx.room3.RoomDatabase
import androidx.room3.RoomDatabaseConstructor
import kpt.core.database.infra.dao.BookkeeperDao
import kpt.core.database.infra.dao.DraftDao
import kpt.core.database.infra.dao.FetchedAtDao
import kpt.core.database.infra.entity.BookkeeperEntity
import kpt.core.database.infra.entity.DraftEntity
import kpt.core.database.infra.entity.FetchedAtEntity
import org.mifos.groupbanking.core.database.fieldofficerdashboard.dao.FieldOfficerDashboardDao
import org.mifos.groupbanking.core.database.fieldofficerdashboard.entity.FieldOfficerDashboardCacheEntity
import org.mifos.groupbanking.core.database.groupdashboard.dao.GroupDashboardDao
import org.mifos.groupbanking.core.database.groupdashboard.entity.GroupDashboardCacheEntity
import org.mifos.groupbanking.core.database.grouplist.dao.GroupListDao
import org.mifos.groupbanking.core.database.grouplist.entity.GroupListEntity
import org.mifos.groupbanking.core.database.grouptypepicker.dao.GroupTypeConfigDao
import org.mifos.groupbanking.core.database.grouptypepicker.entity.GroupTypeConfigEntity
import org.mifos.groupbanking.core.database.loandetail.dao.LoanDetailDao
import org.mifos.groupbanking.core.database.loandetail.entity.LoanDetailCacheEntity
import org.mifos.groupbanking.core.database.loanlist.dao.LoanListDao
import org.mifos.groupbanking.core.database.loanlist.entity.LoanListEntity
import org.mifos.groupbanking.core.database.meetingcalendar.dao.MeetingCalendarDao
import org.mifos.groupbanking.core.database.meetingcalendar.entity.MeetingCalendarCacheEntity
import org.mifos.groupbanking.core.database.meetingsummary.dao.MeetingRecordDao
import org.mifos.groupbanking.core.database.meetingsummary.entity.MeetingRecordCacheEntity
import org.mifos.groupbanking.core.database.memberlist.dao.MemberListDao
import org.mifos.groupbanking.core.database.memberlist.entity.MemberListEntity
import org.mifos.groupbanking.core.database.memberprofile.dao.MemberProfileCacheDao
import org.mifos.groupbanking.core.database.memberprofile.entity.MemberProfileCacheEntity
import org.mifos.groupbanking.core.database.organizerdashboard.dao.OrganizerDashboardDao
import org.mifos.groupbanking.core.database.organizerdashboard.entity.OrganizerDashboardCacheEntity
import org.mifos.groupbanking.core.database.personaldashboard.dao.MemberDashboardDao
import org.mifos.groupbanking.core.database.personaldashboard.entity.MemberDashboardCacheEntity
import org.mifos.groupbanking.core.database.previousmeetingreview.dao.MeetingAttendanceDao
import org.mifos.groupbanking.core.database.previousmeetingreview.entity.MeetingAttendanceCacheEntity
import org.mifos.groupbanking.core.database.syncqueue.dao.SyncQueueDao
import org.mifos.groupbanking.core.database.syncqueue.entity.SyncQueueEntity

/**
 * KSP-generated constructor bridge for [AppDatabase].
 *
 * Room 3 requires an `expect object` annotated via [@ConstructedBy][ConstructedBy] so that
 * the KSP compiler plugin can generate a platform-specific `actual object` containing the
 * `AppDatabase_Impl` instantiation logic.
 */
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}

/**
 * Root Room 3 database for the application.
 *
 * This is a **commonMain** definition that works across all Kotlin Multiplatform targets
 * (Android, Desktop/JVM, iOS/Native, JS, WasmJS). Platform-specific database creation
 * is handled by [kpt.core.base.database.AppDatabaseFactory] in each platform's
 * DI module — see [kpt.core.database.di.DatabaseModule].
 *
 * Room 3 uses the [ConstructedBy] annotation to delegate instance creation to
 * [AppDatabaseConstructor], whose `actual` implementation is generated by KSP on
 * every target.
 *
 * ## Demo demarcation (showcase-framework-separation)
 * The `infra` entities/DAOs (`Bookkeeper·Draft·FetchedAt`) are framework — always kept.
 * The demo entities/DAOs/converters + the `@AutoMigration` history + the `@DeleteTable`
 * spec are wrapped in demo-marked blocks. `customizer --clean`
 * deletes the `core/database/demo/` packages AND strips these blocks (and resets `VERSION` to a
 * fresh-fork baseline of `1`, dropping the migration history that only existing installs
 * need) — leaving a valid framework-only `@Database` that compiles. The Room 3 impl itself
 * is unchanged; the markers are comments and are behavior-neutral until stripped.
 *
 * ## Schema history
 * | Version | Change |
 * |---------|--------|
 * | v3 → v4 | adds `framework_fetched_at` |
 * | v4 → v5 | adds `framework_submit_drafts` |
 * | v5 → v6 | adds `personal_watchlist` |
 * | v6 → v7 | adds `uniqueKey` column to drafts |
 * | v7 → v8 | adds `banking_loans` + `banking_bill_reminders` |
 * | v8 → v10 | adds `alerts` + `interest_rate_series`; drops `samples` ([MigrationSpec8to10]) |
 * | v2 → v3 | adds `group_list_cache` (group-list paginated offline cache, COMP-GRP-001) |
 * | v3 → v4 | adds `member_dashboard_cache` (personal-dashboard per-group offline cache, COMP-DASH-001) |
 * | v4 → v5 | adds `group_dashboard_cache` (group-dashboard composite per-group offline cache, COMP-GRP-001) |
 * | v5 → v6 | adds `member_list_cache` (member-list paginated per-group offline cache, GET /groups/{groupId}/clients) |
 * | v6 → v7 | adds `member_profile_cache` (member-profile composite per-client offline cache, get_client + get_client_accounts + get_member_role) |
 * | v7 → v8 | adds `loan_list_cache` (loan-list paginated per-group offline cache, GET /groups/{groupId}/loans) |
 * | v8 → v9 | adds `loan_detail_cache` (loan-detail single-key composite offline cache, GET /loans/{loanId}) |
 * | v9 → v10 | adds `sync_queue` (offline write-queue shared infra — member-add/loan-request enqueue, sync-status read; NOT a Store5 read-cache) |
 */
@Database(
    entities = [
        // infra (framework) — always kept
        BookkeeperEntity::class,
        FetchedAtEntity::class,
        DraftEntity::class,
        // group-banking domain — group-type-picker seeded catalogue cache (COMP-DT-003)
        GroupTypeConfigEntity::class,
        // group-banking domain — group-list paginated offline cache (COMP-GRP-001)
        GroupListEntity::class,
        // group-banking domain — personal-dashboard per-group offline cache (COMP-DASH-001)
        MemberDashboardCacheEntity::class,
        // group-banking domain — group-dashboard composite per-group offline cache (COMP-GRP-001)
        GroupDashboardCacheEntity::class,
        // group-banking domain — member-list paginated per-group offline cache (GET /groups/{groupId}/clients)
        MemberListEntity::class,
        // group-banking domain — member-profile composite per-client offline cache (get_client + get_client_accounts + get_member_role)
        MemberProfileCacheEntity::class,
        // group-banking domain — loan-list paginated per-group offline cache (GET /groups/{groupId}/loans)
        LoanListEntity::class,
        // group-banking domain — loan-detail single-key composite offline cache (GET /loans/{loanId})
        LoanDetailCacheEntity::class,
        // group-banking domain — offline write-queue shared infra (member-add / loan-request enqueue,
        // sync-status read); NOT a Store5 read-cache
        SyncQueueEntity::class,
        // group-banking domain — meeting-summary single-key composite offline cache (GET /datatables/dt_meeting_record/{groupId})
        MeetingRecordCacheEntity::class,
        // group-banking domain — meeting-calendar single-key offline cache (GET /datatables/dt_meeting_schedule/{groupId} + dt_meeting_record)
        MeetingCalendarCacheEntity::class,
        // group-banking domain — field-officer-dashboard aggregate per-staff offline cache (FR-009,
        // parallel GET /groups fanned into cross-group KPIs + group health list)
        FieldOfficerDashboardCacheEntity::class,
        // group-banking domain — organizer-dashboard single-key hub offline cache
        // (GET /companion/organizer/dashboard — "my groups" KPIs + today's schedule + recent activity)
        OrganizerDashboardCacheEntity::class,
        // group-banking domain — previous-meeting-review per-member attendance offline cache
        // (GET /datatables/dt_meeting_attendance/{meetingId}, keyed by meetingId)
        MeetingAttendanceCacheEntity::class,
    ],
    version = AppDatabase.VERSION,
    exportSchema = true,
)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {

    // infra (framework) — always kept
    abstract val bookkeeperDao: BookkeeperDao
    abstract val fetchedAtDao: FetchedAtDao
    abstract val draftDao: DraftDao

    // group-banking domain
    abstract val groupTypeConfigDao: GroupTypeConfigDao
    abstract val groupListDao: GroupListDao
    abstract val memberDashboardDao: MemberDashboardDao
    abstract val groupDashboardDao: GroupDashboardDao
    abstract val memberListDao: MemberListDao
    abstract val memberProfileDao: MemberProfileCacheDao
    abstract val loanListDao: LoanListDao
    abstract val loanDetailDao: LoanDetailDao
    abstract val syncQueueDao: SyncQueueDao
    abstract val meetingRecordDao: MeetingRecordDao
    abstract val meetingCalendarDao: MeetingCalendarDao
    abstract val fieldOfficerDashboardDao: FieldOfficerDashboardDao
    abstract val organizerDashboardDao: OrganizerDashboardDao
    abstract val meetingAttendanceDao: MeetingAttendanceDao

    companion object {
        // NOTE: `customizer --clean` resets VERSION to 1 (fresh-fork baseline) via a
        // targeted sed, since the migration history above is stripped with the demo block.
        // v1 → v2: adds `group_type_config` (group-type-picker offline cache).
        // v2 → v3: adds `group_list_cache` (group-list paginated offline cache, COMP-GRP-001).
        // v3 → v4: adds `member_dashboard_cache` (personal-dashboard per-group offline cache, COMP-DASH-001).
        // v4 → v5: adds `group_dashboard_cache` (group-dashboard composite per-group offline cache, COMP-GRP-001).
        // v5 → v6: adds `member_list_cache` (member-list paginated per-group offline cache, GET /groups/{groupId}/clients).
        // v6 → v7: adds `member_profile_cache` (member-profile composite per-client offline cache, get_client + get_client_accounts + get_member_role).
        // v7 → v8: adds `loan_list_cache` (loan-list paginated per-group offline cache, GET /groups/{groupId}/loans).
        // v8 to v9: adds `loan_detail_cache` (loan-detail single-key composite offline cache, GET /loans/{loanId}).
        // v9 to v10: adds `sync_queue` (offline write-queue shared infra — member-add/loan-request
        //            enqueue, sync-status read; NOT a Store5 read-cache).
        // v10 to v11: adds `meeting_record_cache` (meeting-summary single-key composite offline
        //            cache, GET /datatables/dt_meeting_record/{groupId}).
        // v11 to v12: adds `meeting_calendar_cache` (meeting-calendar single-key offline cache,
        //            GET /datatables/dt_meeting_schedule/{groupId} merged with dt_meeting_record).
        // v12 to v13: adds `field_officer_dashboard_cache` (field-officer-dashboard aggregate
        //            per-staff offline cache, FR-009 — parallel GET /groups).
        // v13 to v14: adds `organizer_dashboard_cache` (organizer-dashboard single-key hub offline
        //            cache, GET /companion/organizer/dashboard — "my groups" KPIs + today's schedule
        //            + recent activity).
        // v14 to v15: adds `meeting_attendance_cache` (previous-meeting-review per-member attendance
        //            offline cache, GET /datatables/dt_meeting_attendance/{meetingId}).
        // v15 to v16: adds clientId / groupLinkedSavingsId / individualSavingsId columns to
        //            `member_dashboard_cache` (member-identity + savings-account ids forwarded to
        //            the personal-savings nav_params).
        // v16 to v17: adds `meeting_time` column to `meeting_record_cache` (the wall-clock time the
        //            meeting was conducted — dt_meeting_record.completed_time, shown on the calendar
        //            list + summary + previous-review).
        // Fresh forks with no released installs pick this up via fallbackToDestructiveMigration.
        const val VERSION = 17

        /** Fork-unique on-disk DB filename — single source of truth is [DatabaseConfig.NAME]
         *  (appId-derived, regenerated by `syncForkConfig`). All platform builders read this. */
        const val DATABASE_NAME = DatabaseConfig.NAME
    }
}
