/*
 * Copyright 2025 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */
package kpt.core.database

import androidx.room3.ConstructedBy
import androidx.room3.Database
import androidx.room3.RoomDatabase
import androidx.room3.RoomDatabaseConstructor
import kpt.core.database.infra.dao.BookkeeperDao
import kpt.core.database.infra.dao.DraftDao
import kpt.core.database.infra.dao.FetchedAtDao
import kpt.core.database.infra.entity.BookkeeperEntity
import kpt.core.database.infra.entity.DraftEntity
import kpt.core.database.infra.entity.FetchedAtEntity
import org.mifos.groupbanking.core.database.grouplist.dao.GroupListDao
import org.mifos.groupbanking.core.database.grouplist.entity.GroupListEntity
import org.mifos.groupbanking.core.database.grouptypepicker.dao.GroupTypeConfigDao
import org.mifos.groupbanking.core.database.grouptypepicker.entity.GroupTypeConfigEntity
import org.mifos.groupbanking.core.database.groupdashboard.dao.GroupDashboardDao
import org.mifos.groupbanking.core.database.groupdashboard.entity.GroupDashboardCacheEntity
import org.mifos.groupbanking.core.database.memberlist.dao.MemberListDao
import org.mifos.groupbanking.core.database.memberlist.entity.MemberListEntity
import org.mifos.groupbanking.core.database.memberprofile.dao.MemberProfileCacheDao
import org.mifos.groupbanking.core.database.memberprofile.entity.MemberProfileCacheEntity
import org.mifos.groupbanking.core.database.personaldashboard.dao.MemberDashboardDao
import org.mifos.groupbanking.core.database.personaldashboard.entity.MemberDashboardCacheEntity

/**
 * KSP-generated constructor bridge for [AppDatabase].
 *
 * Room 3 requires an `expect object` annotated via [@ConstructedBy][ConstructedBy] so that
 * the KSP compiler plugin can generate a platform-specific `actual object` containing the
 * `AppDatabase_Impl` instantiation logic.
 */
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}

/**
 * Root Room 3 database for the application.
 *
 * This is a **commonMain** definition that works across all Kotlin Multiplatform targets
 * (Android, Desktop/JVM, iOS/Native, JS, WasmJS). Platform-specific database creation
 * is handled by [kpt.core.base.database.AppDatabaseFactory] in each platform's
 * DI module — see [kpt.core.database.di.DatabaseModule].
 *
 * Room 3 uses the [ConstructedBy] annotation to delegate instance creation to
 * [AppDatabaseConstructor], whose `actual` implementation is generated by KSP on
 * every target.
 *
 * ## Demo demarcation (showcase-framework-separation)
 * The `infra` entities/DAOs (`Bookkeeper·Draft·FetchedAt`) are framework — always kept.
 * The demo entities/DAOs/converters + the `@AutoMigration` history + the `@DeleteTable`
 * spec are wrapped in demo-marked blocks. `customizer --clean`
 * deletes the `core/database/demo/` packages AND strips these blocks (and resets `VERSION` to a
 * fresh-fork baseline of `1`, dropping the migration history that only existing installs
 * need) — leaving a valid framework-only `@Database` that compiles. The Room 3 impl itself
 * is unchanged; the markers are comments and are behavior-neutral until stripped.
 *
 * ## Schema history
 * | Version | Change |
 * |---------|--------|
 * | v3 → v4 | adds `framework_fetched_at` |
 * | v4 → v5 | adds `framework_submit_drafts` |
 * | v5 → v6 | adds `personal_watchlist` |
 * | v6 → v7 | adds `uniqueKey` column to drafts |
 * | v7 → v8 | adds `banking_loans` + `banking_bill_reminders` |
 * | v8 → v10 | adds `alerts` + `interest_rate_series`; drops `samples` ([MigrationSpec8to10]) |
 * | v2 → v3 | adds `group_list_cache` (group-list paginated offline cache, COMP-GRP-001) |
 * | v3 → v4 | adds `member_dashboard_cache` (personal-dashboard per-group offline cache, COMP-DASH-001) |
 * | v4 → v5 | adds `group_dashboard_cache` (group-dashboard composite per-group offline cache, COMP-GRP-001) |
 * | v5 → v6 | adds `member_list_cache` (member-list paginated per-group offline cache, GET /groups/{groupId}/clients) |
 * | v6 → v7 | adds `member_profile_cache` (member-profile composite per-client offline cache, get_client + get_client_accounts + get_member_role) |
 */
@Database(
    entities = [
        // infra (framework) — always kept
        BookkeeperEntity::class,
        FetchedAtEntity::class,
        DraftEntity::class,
        // group-banking domain — group-type-picker seeded catalogue cache (COMP-DT-003)
        GroupTypeConfigEntity::class,
        // group-banking domain — group-list paginated offline cache (COMP-GRP-001)
        GroupListEntity::class,
        // group-banking domain — personal-dashboard per-group offline cache (COMP-DASH-001)
        MemberDashboardCacheEntity::class,
        // group-banking domain — group-dashboard composite per-group offline cache (COMP-GRP-001)
        GroupDashboardCacheEntity::class,
        // group-banking domain — member-list paginated per-group offline cache (GET /groups/{groupId}/clients)
        MemberListEntity::class,
        // group-banking domain — member-profile composite per-client offline cache (get_client + get_client_accounts + get_member_role)
        MemberProfileCacheEntity::class,
    ],
    version = AppDatabase.VERSION,
    exportSchema = true,
)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {

    // infra (framework) — always kept
    abstract val bookkeeperDao: BookkeeperDao
    abstract val fetchedAtDao: FetchedAtDao
    abstract val draftDao: DraftDao

    // group-banking domain
    abstract val groupTypeConfigDao: GroupTypeConfigDao
    abstract val groupListDao: GroupListDao
    abstract val memberDashboardDao: MemberDashboardDao
    abstract val groupDashboardDao: GroupDashboardDao
    abstract val memberListDao: MemberListDao
    abstract val memberProfileDao: MemberProfileCacheDao

    companion object {
        // NOTE: `customizer --clean` resets VERSION to 1 (fresh-fork baseline) via a
        // targeted sed, since the migration history above is stripped with the demo block.
        // v1 → v2: adds `group_type_config` (group-type-picker offline cache).
        // v2 → v3: adds `group_list_cache` (group-list paginated offline cache, COMP-GRP-001).
        // v3 → v4: adds `member_dashboard_cache` (personal-dashboard per-group offline cache, COMP-DASH-001).
        // v4 → v5: adds `group_dashboard_cache` (group-dashboard composite per-group offline cache, COMP-GRP-001).
        // v5 → v6: adds `member_list_cache` (member-list paginated per-group offline cache, GET /groups/{groupId}/clients).
        // v6 → v7: adds `member_profile_cache` (member-profile composite per-client offline cache, get_client + get_client_accounts + get_member_role).
        // Fresh forks with no released installs pick this up via fallbackToDestructiveMigration.
        const val VERSION = 7

        /** Fork-unique on-disk DB filename — single source of truth is [DatabaseConfig.NAME]
         *  (appId-derived, regenerated by `syncForkConfig`). All platform builders read this. */
        const val DATABASE_NAME = DatabaseConfig.NAME
    }
}
